sudo: required

services:
  - docker

before_install:
  - docker build -t test/planet-sympy .
  - docker ps -a

script:
  - ls
  - docker run test/planet-sympy /bin/sh -c "./update.sh"

env:
  global:
    secure: "oyaTNI0Cq5gYhXmQp6BMFSSAw6UAhGJbtCBDXiDbx22sLeyX9bLM+V3MiuJj9GcojlTUbf66VNMTd6GDJr4vToX1KvJei4QNHstE0GpT2ZpgQFzEQUx5+5ENKVLe/JjB+W3HKIwFItTt0lBA1MbqzgoQKtp85mJ/pKTv2U6t1/Sr7TAkIJnuEsrf0+4miMfikOKM8MwblayqhYDl9W6SySEuYafFUtmtS6WhMRJAqFGKb/rsWThBjJkedK9e/vbggsf2hWGkTKewMzFrpeN8W/ITBDYw5Y1k+/kyKhrN9Il+b74L7oeVMbhvuHm4masn0YaqIig7dCCJ1KkdGGwtrCo4MH1C0W1BuzxJj+x7LZl6mgO54/gE4jXF3Sbc8/1wPnTc8DwQLJjPpjyCKbuvk2RAUQcD+5iyi4qMXi91Op3b8g7pK2ONzoy0SMFYFZIbpmr06DsvRPiZBSMvgT8FV38LCq7fhHRbFuHwYizmxLp5X7KoUVqKjCtOvq1I3ulvJ6cpJ5UxdmX6yocDG6kgBFqNveIXGNvGfljG4gtcLMLdG4Uu7sVI23LHHmpF60POxqjDNnCRXrFJ5wrKZKTxNvpm3ta07k3AZrRjAs7uD3MZwpTsevKz689SnQEBa5UVsdZTH38lZAoBI4DC/82MuvGwx42+Mgto9UKW+YA2s2U="

notifications:
  email: false
