sudo: required

services:
  - docker

before_install:
  - docker build -t test/planet-sympy .
  - docker ps -a

script:
  - echo "TOKEN: ${GH_TOKEN2}"
  - bin/test_travis.sh

notifications:
  email: false
